# Generated by Django 5.2.17 on 2026-08-12 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('top_products', models.JSONField(blank=True, default=list)),
                ('markdown_context', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_report_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_date', 'to_date'], name='reports_sal_from_da_c9a747_idx'), models.Index(fields=['-created_at'], name='reports_sal_created_4e1c66_idx')],
            },
        ),
    ]
