# Generated by Django 5.2.17 on 2026-08-12 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('permissions', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['role_code'],
                'indexes': [models.Index(fields=['role_code'], name='accounts_ro_role_co_b48f3f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=80)),
                ('prompt_summary', models.CharField(max_length=255)),
                ('response_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('fallback', 'Fallback'), ('error', 'Error'), ('human_review', 'Human review')], max_length=30)),
                ('fallback_message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_event_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purpose', '-created_at'], name='accounts_ai_purpose_b45600_idx'), models.Index(fields=['status', '-created_at'], name='accounts_ai_status_b50525_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('business', 'Business'), ('authorization', 'Authorization')], max_length=30)),
                ('action', models.CharField(max_length=100)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='accounts_au_event_t_03bfa1_idx'), models.Index(fields=['user', '-created_at'], name='accounts_au_user_id_14f360_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('locked', 'Locked'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='accounts.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
                'indexes': [models.Index(fields=['status'], name='accounts_us_status_aa9625_idx')],
            },
        ),
    ]
