# Generated by Django 6.0.4 on 2026-04-23 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='Số hóa đơn')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Khách hàng')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày bán')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng tiền')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên bán')),
            ],
            options={
                'verbose_name': 'Hóa đơn bán',
                'verbose_name_plural': 'Hóa đơn bán',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Đơn giá bán')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Thành tiền')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales_invoices.salesinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Sản phẩm')),
            ],
        ),
    ]
