# Generated by Django 6.0.4 on 2026-04-23 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '__first__'),
        ('sales_invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='customers.customer', verbose_name='Khách hàng'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Chiết khấu'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Thanh toán'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Thuế (VAT)'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng cộng'),
        ),
    ]
