# Generated by Django 6.0.4 on 2026-04-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=20, unique=True, verbose_name='Mã nhóm')),
                ('group_name', models.CharField(max_length=100, verbose_name='Tên nhóm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Nhóm sản phẩm',
                'verbose_name_plural': 'Các nhóm sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
    ]
