# Generated by Django 6.0.4 on 2026-04-23 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='Số hóa đơn')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Nhà cung cấp')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày nhập')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng tiền')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Hóa đơn nhập',
                'verbose_name_plural': 'Hóa đơn nhập',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Đơn giá nhập')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Thành tiền')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='purchase_invoices.purchaseinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Sản phẩm')),
            ],
        ),
    ]
