# Generated by Django 6.0.4 on 2026-04-23 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_invoices', '0001_initial'),
        ('suppliers', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='suppliers.supplier', verbose_name='Nhà cung cấp'),
        ),
    ]
